<?php
require_once 'config/config.php';
require_once 'config/pdf_excel_config.php';

echo "<h2>Testing Library Installation</h2>";

// Test PhpSpreadsheet
echo "<h3>PhpSpreadsheet:</h3>";
if (class_exists('PhpOffice\\PhpSpreadsheet\\Spreadsheet')) {
    echo "✓ PhpSpreadsheet is installed correctly<br>";

    $testExcel = new ExcelGenerator();
    $testExcel->setProperties("Test Document");
    $testExcel->addTitle("Test Excel File", 1);
    $testExcel->setHeaders(['Column 1', 'Column 2', 'Column 3'], 2);
    $testExcel->addData([
        ['Data 1', 'Data 2', 'Data 3'],
        ['Data 4', 'Data 5', 'Data 6']
    ], 3);

    echo "✓ Excel generator working<br>";
} else {
    echo "✗ PhpSpreadsheet not found<br>";
}

// Test Dompdf
echo "<h3>Dompdf:</h3>";
if (class_exists('Dompdf\\Dompdf')) {
    echo "✓ Dompdf is installed correctly<br>";

    $testPdf = new PDFGenerator();
    $html = getPDFStyles() . "<h1>Test PDF</h1><p>This is a test PDF generated by Dompdf.</p>";

    echo "✓ PDF generator working<br>";
} else {
    echo "✗ Dompdf not found<br>";
}

echo "<hr>";
echo "<h4>Installation Status:</h4>";
echo "<ul>";
echo "<li>Composer autoload: " . (file_exists('vendor/autoload.php') ? "✓ Found" : "✗ Not found") . "</li>";
echo "<li>Temp directory: " . (is_writable('temp') ? "✓ Writable" : "✗ Not writable") . "</li>";
echo "<li>Fonts directory: " . (is_writable('fonts') ? "✓ Writable" : "✗ Not writable") . "</li>";
echo "</ul>";
